### ISSUE TITLE
Connector part numbers

### ISSUE THREAD

**Issue by OzzieOrca** [bluekitchen/arm-cortex-tc2050-adapter#1]
What connector part number did you use for the TC-2050-IDC connector? Looks like the connector is 0.05" pitch but the board seems to have the same 0.1" through holes as the other connector.

If you have the part numbers for the others, that could be nice but I'll probably use 0.1" pin headers.

Thanks :)

I'm just trying to find an easy way to connect my STLINK-V3MINI to a dev board with standard pin headers.

**Comment by OzzieOrca** [comment]
Nvm, I think https://www.adafruit.com/product/2743 is actually what I want. Seems this adapter is for a 0.1" pitch connector ribbon cable which isn't what I have.

**Comment by mringwal** [comment]
This adapter is for use with a TAG Connect cable, which has a 0.1" 10-pin header.
For 20-pin JTAG header the adafruit breakout should work.
For 10-pin 0.05" ARM Cortex JTAG, you need something like this: https://www.segger.com/products/debug-probes/j-link/accessories/adapters/9-pin-cortex-m-adapter/ (cheaper options are available, too)
